# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refNumber', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='stopTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refNumber', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='tourTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refNumber', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=10000)),
                ('country', django_countries.fields.CountryField(default='gb', max_length=2)),
                ('travelClass', models.IntegerField(choices=[(1, 'Backpacker'), (2, 'Budget'), (3, 'Standard')])),
                ('stops', models.CharField(max_length=300)),
            ],
        ),
    ]
