# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourtable',
            name='stops',
        ),
    ]
