# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tourtable_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourtable',
            name='stops',
            field=models.CharField(default=datetime.datetime(2016, 7, 6, 16, 21, 15, 527581, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
