# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourtable_stops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='activities',
        ),
        migrations.AddField(
            model_name='stoptable',
            name='activityTitle',
            field=models.CharField(default=datetime.datetime(2016, 7, 6, 16, 27, 41, 258677, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoptable',
            name='activityTitleDescription',
            field=models.TextField(default=datetime.datetime(2016, 7, 6, 16, 27, 46, 692493, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
    ]
