# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20160706_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refNumber', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='stoptable',
            name='activityTitle',
        ),
        migrations.RemoveField(
            model_name='stoptable',
            name='activityTitleDescription',
        ),
        migrations.RemoveField(
            model_name='tourtable',
            name='stops',
        ),
        migrations.AddField(
            model_name='stoptable',
            name='tour',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='tours.tourTable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.stopTable'),
        ),
    ]
