# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20160708_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourtable',
            name='country',
            field=models.CharField(max_length=40),
        ),
    ]
