# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20160824_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptable',
            name='lengthofstay',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
