# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotelRoomTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('beds', models.CharField(max_length=100)),
                ('amenities', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='hotelTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refNumber', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=10000)),
                ('stop', models.CharField(max_length=40)),
                ('travelClass', models.CharField(max_length=40)),
                ('eanhotelid', models.IntegerField(max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('roomtypes', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=40)),
                ('amenities', models.TextField(max_length=10000)),
                ('policies', models.TextField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='hotelroomtypes',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotelTable'),
        ),
    ]
