# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hoteltable_roomtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtypes',
            name='refNumber',
            field=models.CharField(default='ref1', max_length=40),
            preserve_default=False,
        ),
    ]
