# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotelroomtypes_refnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteltable',
            name='ratecode',
            field=models.IntegerField(default=2345678, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteltable',
            name='roomtypecode',
            field=models.IntegerField(default=2345678, max_length=2000),
            preserve_default=False,
        ),
    ]
